name: CD Workflow

on:
  push:
    branches: [master, homolog, production]
  pull_request:
    branches: ['**']

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        node-version: [14.x]
    steps:
    - name: Pegar o nome da branch atual
      shell: bash
      run: echo "::set-output name=current_branch::${{github.event_name}}"
      id: branch_ref

    - name: Instalar o node version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: npm install

    - name: Build
      run: npm run build

  run_test:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        node-version: [14.x]
    steps:
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=current_branch::${GITHUB_REF#refs/heads/}"
        id: branch_ref
      
      - name: Install node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: NPM Install
        run:
          npm install
      
      - name: Run Tests
        run: npm run test:unit